### ISSUE TITLE
Uncaught Error: Cannot find module '../native'

### ISSUE THREAD

**Issue by igorcmelo** [termhn/nanopow-rs-node#2]
**Steps to reproduce:**
1. Install Rust
2. `npm init -y`
3. `npm i nanopow-rs-node`
4. `require('nanopow-rs-node')`

```
Uncaught Error: Cannot find module '../native'
Require stack:
- /tmp/node_modules/nanopow-rs-node/lib/index.js
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/tmp/node_modules/nanopow-rs-node/lib/index.js', '<repl>' ]
}
```

**Comment by fu5ha** [comment]
I've published a new version that should hopefully fix this :)

**Comment by fu5ha** [comment]
Closing this, lmk if it doesn't work for you.
